sudo: required
dist: trusty

language: node_js

cache:
  directories:
    - $HOME/.npm

install:
  - export CURRENT_PACKAGE=$(pwd)
  - cd $CURRENT_PACKAGE/tests
  - meteor npm install --save-dev phantomjs-prebuilt
  - meteor npm install

script:
  - meteor npm run testcli